name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Issue to Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}  # Reference the project ID from a secret
          STATUS_COLUMN_ID: ${{ secrets.STATUS_COLUMN_ID }}  # Replace with the ID of the status column
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          # Add the issue to the project
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/$PROJECT_ID/columns/$STATUS_COLUMN_ID/cards \
            -d "{\"content_id\": $ISSUE_NUMBER, \"content_type\": \"Issue\"}"
